#ifndef DEFINES_H
#define DEFINES_H

enum movement { GOESDOWN, STAY, GOESUP };

#define FLOOR_PASS 5000
#define CLOSE_OPEN_TIME 5000
#define PASSENGER_WAITING 5000
#define FLOOR_AMOUNT 16

#endif // DEFINES_H
