#ifndef DEFINES_H
#define DEFINES_H


#define FLOOR_PASS_TIME 1000
#define OPEN_CLOSE_DOOR_TIME 1500
#define PASSENGER_TIME_SERVICE 4000

#define FLOORS_AMOUNT 16

#define START_FLOOR 1
#define NO_DESTINATION_FLOOR -666

enum direction { DOWN = -1, STAND = 0, UP = 1 };

#endif // DEFINES_H
